-- Desligamento estruturado + acompanhamento interno de vagas.
-- Aplicada no Supabase em 2026-08-22.

create table if not exists public.kt_offboardings (
  id uuid primary key default gen_random_uuid(), colaborador_id text not null references public.kt_colaboradores(id) on delete restrict,
  filial text not null, tipo text not null check (tipo in ('pedido_demissao','dispensa_sem_justa_causa','justa_causa','termino_experiencia','outro')),
  motivo text not null, fato_em date, comunicado_em date not null, ultimo_dia_em date, recontratavel boolean,
  status text not null default 'aguardando_rh' check (status in ('rascunho','aguardando_rh','aprovado','cancelado')),
  iniciado_por uuid references public.kt_perfis(id) on delete set null, revisado_por uuid references public.kt_perfis(id) on delete set null,
  revisado_em timestamptz, observacao_rh text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists kt_offboarding_colab_idx on public.kt_offboardings(colaborador_id,created_at desc);
create index if not exists kt_offboarding_filial_status_idx on public.kt_offboardings(filial,status);

create table if not exists public.kt_offboarding_checklist (
  id uuid primary key default gen_random_uuid(), offboarding_id uuid not null references public.kt_offboardings(id) on delete cascade,
  item_key text not null,label text not null,concluido boolean not null default false,concluido_por uuid references public.kt_perfis(id) on delete set null,
  concluido_em timestamptz,observacao text,created_at timestamptz not null default now(),unique(offboarding_id,item_key)
);
create index if not exists kt_offboarding_checklist_parent_idx on public.kt_offboarding_checklist(offboarding_id);
alter table public.kt_offboardings enable row level security;
alter table public.kt_offboarding_checklist enable row level security;

create policy kt_offboarding_select on public.kt_offboardings for select to authenticated using ((public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('offboarding','view')) or (public.kt_current_profile_type()='gestor' and filial=public.kt_current_profile_filial()));
create policy kt_offboarding_insert on public.kt_offboardings for insert to authenticated with check ((public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('offboarding','edit')) or (public.kt_current_profile_type()='gestor' and filial=public.kt_current_profile_filial() and iniciado_por=auth.uid() and status in ('rascunho','aguardando_rh')));
create policy kt_offboarding_update on public.kt_offboardings for update to authenticated using ((public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('offboarding','edit')) or (public.kt_current_profile_type()='gestor' and filial=public.kt_current_profile_filial() and status in ('rascunho','aguardando_rh') and revisado_em is null)) with check ((public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('offboarding','edit')) or (public.kt_current_profile_type()='gestor' and filial=public.kt_current_profile_filial() and status in ('rascunho','aguardando_rh') and revisado_em is null));
create policy kt_offboarding_delete on public.kt_offboardings for delete to authenticated using (public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('offboarding','delete') and status in ('rascunho','cancelado'));
create policy kt_offboarding_checklist_select on public.kt_offboarding_checklist for select to authenticated using (exists(select 1 from public.kt_offboardings o where o.id=offboarding_id and ((public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('offboarding','view')) or (public.kt_current_profile_type()='gestor' and o.filial=public.kt_current_profile_filial()))));
create policy kt_offboarding_checklist_write on public.kt_offboarding_checklist for all to authenticated using (exists(select 1 from public.kt_offboardings o where o.id=offboarding_id and ((public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('offboarding','edit')) or (public.kt_current_profile_type()='gestor' and o.filial=public.kt_current_profile_filial() and o.status in ('rascunho','aguardando_rh'))))) with check (exists(select 1 from public.kt_offboardings o where o.id=offboarding_id and ((public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('offboarding','edit')) or (public.kt_current_profile_type()='gestor' and o.filial=public.kt_current_profile_filial() and o.status in ('rascunho','aguardando_rh')))));

create or replace function public.kt_offboarding_seed_checklist() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.kt_offboarding_checklist(offboarding_id,item_key,label) values (new.id,'uniforme','Devolução de uniforme'),(new.id,'cracha','Devolução de crachá/chaves'),(new.id,'acessos','Revogação de acessos e senhas'),(new.id,'equipamentos','Devolução de equipamentos/itens da empresa') on conflict do nothing; return new; end; $$;
revoke all on function public.kt_offboarding_seed_checklist() from public,anon,authenticated;
drop trigger if exists trg_kt_offboarding_seed_checklist on public.kt_offboardings; create trigger trg_kt_offboarding_seed_checklist after insert on public.kt_offboardings for each row execute function public.kt_offboarding_seed_checklist();

create or replace function public.kt_offboarding_sync_case_and_employee() returns trigger language plpgsql security definer set search_path=public as $$ declare v_nome text; v_case_id uuid; begin select nome into v_nome from public.kt_colaboradores where id=new.colaborador_id; insert into public.kt_casos(tipo,origem_tabela,origem_id,filial,titulo,descricao,status,confidencialidade,aberto_por_profile_id,metadata,encerrado_em,encerrado_motivo) values('offboarding','kt_offboardings',new.id::text,new.filial,'Desligamento · '||coalesce(v_nome,'Colaborador'),new.motivo,new.status,'ambos',new.iniciado_por,jsonb_build_object('tipo',new.tipo,'comunicado_em',new.comunicado_em,'ultimo_dia_em',new.ultimo_dia_em,'recontratavel',new.recontratavel),case when new.status in ('aprovado','cancelado') then now() else null end,case when new.status='cancelado' then coalesce(new.observacao_rh,'Processo cancelado') when new.status='aprovado' then 'Desligamento aprovado pelo RH' else null end) on conflict (origem_tabela,origem_id) where origem_tabela is not null and origem_id is not null do update set filial=excluded.filial,titulo=excluded.titulo,descricao=excluded.descricao,status=excluded.status,metadata=excluded.metadata,encerrado_em=excluded.encerrado_em,encerrado_motivo=excluded.encerrado_motivo,updated_at=now() returning id into v_case_id; insert into public.kt_caso_envolvidos(caso_id,colaborador_id,nome_snapshot,papel) select v_case_id,new.colaborador_id,v_nome,'mencionado' where not exists(select 1 from public.kt_caso_envolvidos where caso_id=v_case_id and colaborador_id=new.colaborador_id and papel='mencionado'); if new.status='aprovado' and old.status is distinct from new.status then update public.kt_colaboradores set ativo=false,motivo_desligamento=new.motivo,desligamento_informado_em=new.comunicado_em,ultimo_dia_em=new.ultimo_dia_em,desligado_em=(extract(epoch from now())*1000)::bigint,desligado_por=coalesce((select nome from public.kt_perfis where id=new.revisado_por),'RH'),updated_at=now() where id=new.colaborador_id; end if; return new; end; $$;
revoke all on function public.kt_offboarding_sync_case_and_employee() from public,anon,authenticated;
drop trigger if exists trg_kt_offboarding_sync on public.kt_offboardings; create trigger trg_kt_offboarding_sync after insert or update on public.kt_offboardings for each row execute function public.kt_offboarding_sync_case_and_employee();

alter table public.kt_vagas add column if not exists status text; alter table public.kt_vagas add column if not exists solicitante_id uuid references public.kt_perfis(id) on delete set null; alter table public.kt_vagas add column if not exists status_at timestamptz; alter table public.kt_vagas add column if not exists updated_at timestamptz not null default now(); alter table public.kt_vagas add column if not exists observacao text; alter table public.kt_vagas add column if not exists portal_url text; alter table public.kt_vagas add column if not exists preenchida_em timestamptz; alter table public.kt_vagas add column if not exists cancelada_motivo text; update public.kt_vagas set status='solicitado' where status is null; alter table public.kt_vagas alter column status set default 'solicitado'; alter table public.kt_vagas alter column status set not null; alter table public.kt_vagas drop constraint if exists kt_vagas_status_check; alter table public.kt_vagas add constraint kt_vagas_status_check check (status in ('solicitado','triagem_rh','divulgando','entrevistas','preenchida','cancelada')); create index if not exists kt_vagas_filial_status_idx on public.kt_vagas(filial,status);
create table if not exists public.kt_vaga_historico(id uuid primary key default gen_random_uuid(),vaga_id text not null references public.kt_vagas(id) on delete cascade,actor_id uuid references public.kt_perfis(id) on delete set null,status_anterior text,status_novo text,observacao text,created_at timestamptz not null default now()); create index if not exists kt_vaga_historico_vaga_idx on public.kt_vaga_historico(vaga_id,created_at desc); alter table public.kt_vaga_historico enable row level security;
drop policy if exists kt_write_authenticated on public.kt_vagas;
create policy kt_vagas_select on public.kt_vagas for select to authenticated using ((public.kt_current_profile_type()='gestor' and filial=public.kt_current_profile_filial()) or (public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('vagas','view')));
create policy kt_vagas_insert on public.kt_vagas for insert to authenticated with check ((public.kt_current_profile_type()='gestor' and filial=public.kt_current_profile_filial() and status='solicitado' and solicitante_id=auth.uid()) or (public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('vagas','edit')));
create policy kt_vagas_update on public.kt_vagas for update to authenticated using ((public.kt_current_profile_type()='gestor' and filial=public.kt_current_profile_filial() and status='solicitado') or (public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('vagas','edit'))) with check ((public.kt_current_profile_type()='gestor' and filial=public.kt_current_profile_filial() and status in ('solicitado','cancelada')) or (public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('vagas','edit')));
create policy kt_vaga_historico_select on public.kt_vaga_historico for select to authenticated using (exists(select 1 from public.kt_vagas v where v.id=vaga_id and ((public.kt_current_profile_type()='gestor' and v.filial=public.kt_current_profile_filial()) or (public.kt_current_profile_type() in ('azumi','rh') and public.kt_has_admin_permission('vagas','view')))));
create or replace function public.kt_vaga_audit_and_case() returns trigger language plpgsql security definer set search_path=public as $$ begin if tg_op='INSERT' then insert into public.kt_vaga_historico(vaga_id,actor_id,status_anterior,status_novo,observacao) values(new.id,auth.uid(),null,new.status,'Vaga solicitada.'); elsif new.status is distinct from old.status or new.observacao is distinct from old.observacao then insert into public.kt_vaga_historico(vaga_id,actor_id,status_anterior,status_novo,observacao) values(new.id,auth.uid(),old.status,new.status,new.observacao); end if; new.updated_at=now(); if tg_op='UPDATE' and new.status is distinct from old.status then new.status_at=now(); end if; if new.status='preenchida' and new.preenchida_em is null then new.preenchida_em=now(); end if; return new; end; $$;
revoke all on function public.kt_vaga_audit_and_case() from public,anon,authenticated;
drop trigger if exists trg_kt_vaga_before on public.kt_vagas; create trigger trg_kt_vaga_before before insert or update on public.kt_vagas for each row execute function public.kt_vaga_audit_and_case();
create or replace function public.kt_vaga_sync_case() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.kt_casos(tipo,origem_tabela,origem_id,filial,titulo,descricao,status,confidencialidade,aberto_por_profile_id,metadata,encerrado_em,encerrado_motivo) values('vaga','kt_vagas',new.id,new.filial,'Vaga · '||new.cargo,new.motivo,new.status,'ambos',new.solicitante_id,jsonb_build_object('portal_url',new.portal_url,'observacao',new.observacao),case when new.status in ('preenchida','cancelada') then now() else null end,case when new.status='cancelada' then new.cancelada_motivo when new.status='preenchida' then 'Vaga preenchida' else null end) on conflict (origem_tabela,origem_id) where origem_tabela is not null and origem_id is not null do update set filial=excluded.filial,titulo=excluded.titulo,descricao=excluded.descricao,status=excluded.status,metadata=excluded.metadata,encerrado_em=excluded.encerrado_em,encerrado_motivo=excluded.encerrado_motivo,updated_at=now(); return new; end; $$;
revoke all on function public.kt_vaga_sync_case() from public,anon,authenticated;
drop trigger if exists trg_kt_vaga_sync_case on public.kt_vagas; create trigger trg_kt_vaga_sync_case after insert or update on public.kt_vagas for each row execute function public.kt_vaga_sync_case();
insert into public.kt_casos(tipo,origem_tabela,origem_id,filial,titulo,descricao,status,confidencialidade,aberto_por_profile_id,metadata,encerrado_em,encerrado_motivo) select 'vaga','kt_vagas',v.id,v.filial,'Vaga · '||v.cargo,v.motivo,v.status,'ambos',v.solicitante_id,jsonb_build_object('portal_url',v.portal_url,'observacao',v.observacao),case when v.status in ('preenchida','cancelada') then now() else null end,case when v.status='cancelada' then v.cancelada_motivo when v.status='preenchida' then 'Vaga preenchida' else null end from public.kt_vagas v on conflict do nothing;
